/**
 * Centralized copy for Finance4All — portal, auth, and landing.
 * Tone: specific, member-first, editorial. Lead with what people do, not adjectives.
 */

export const portalCopy = {
  dashboard: {
    eyebrow: "Member home",
    title: "Dashboard",
    todayTab:
      "Today's picks: articles, lab openings, events, and members that match your interests.",
    communityTab: "Chapter counts, open labs, and recent member activity across the network.",
    exploreTab: "All portal modules — news, research, pathways, events, education, and network.",
    chapterSpotlight:
      "Your chapter runs meetups, speaker nights, and workshops. Browse upcoming events and members in your city.",
    exploreIntro:
      "Jump to any module from the sidebar — or use ⌘K to search across the portal.",
    labEmptyTitle: "No lab applications yet",
    labEmptyDescription:
      "Meta Labs lists open research roles with named lead reviewers. Most applications take five minutes — motivation and relevant coursework matter more than a long résumé.",
    newsEmpty:
      "Your chapter hasn't published articles yet. Read live headlines and explainers on Debriefed in the meantime.",
    activityEmpty:
      "Saves, lab applications, event RSVPs, and connections show up here as you use the portal.",
    engagementTitle: "Your activity",
    engagementActive:
      "You've saved articles, applied to labs, or connected with members recently. Your timeline and stats update as you go.",
    engagementStarting:
      "Start with one action: save a Debriefed article, browse open labs, or find someone in your chapter on Network.",
    chapterSpotlightEmpty:
      "Nothing scheduled at your chapter yet. Browse events from other chapters — membership is global.",
    statLabels: {
      saved: "Saved",
      labApps: "Lab apps",
      connections: "Connections",
      events: "Events",
      savedArticles: "Saved articles",
      labApplications: "Lab applications",
      eventsRegistered: "Events registered",
    },
    tabs: {
      today: "Today",
      community: "Community",
      explore: "All modules",
    },
    profileComplete: "Profile {percent}% complete",
    openDebriefed: "Full feed →",
    readExplainers: "Read explainers →",
    quickSaved: "Saved",
    quickActivity: "Activity feed",
    quickSearch: "Search ⌘K",
  },
  debriefed: {
    eyebrow: "Finance Debriefed",
    title: "News & market pulse",
    description:
      "Macro, markets, IPO, and company coverage from Finance4All editors and chapter contributors. Save articles to your library and set digest preferences below.",
    digestNote:
      "Weekly email digests roll out chapter by chapter. Saving your preference here puts you first in line when delivery goes live in your region.",
    liveSection:
      "Headlines refresh from live sources when configured, or from your chapter's published feed.",
    emptyArticles:
      "No articles in this category yet. Try another filter, read explainers for background, or check back after your chapter publishes.",
    digestPreferences: "Digest preferences",
    digestInterested: "Interested in weekly digest",
    preferencesSaved: "Preferences saved",
    substackTitle: "Substack",
    substackBody: "Subscribe to Finance Debriefed on Substack for the weekly digest outside the portal.",
    substackSubscribed: "I'm subscribed",
    substackOpen: "Open Substack",
    marketHeadlines: "Market headlines",
    explainersSection: "Explainers",
    trendingSection: "Trending",
    liveBadge: "Live",
    latestBadge: "Latest",
    chapterBadge: "Chapter",
    categories: {
      all: "All",
      macro: "Macro",
      markets: "Markets",
      ipo: "IPO",
      company: "Company",
    },
  },
  explainers: {
    eyebrow: "Finance Debriefed",
    title: "Explain This",
    description:
      "Short explainers on finance terms and current narratives — each card links to related Catalyst lessons and glossary entries.",
    empty:
      "No explainers published yet. Admins can add cards from the admin panel, or browse the glossary below.",
    notFound: "This explainer could not be found. Browse all cards or search the glossary.",
  },
  labs: {
    eyebrow: "Meta Labs",
    title: "Research projects",
    description:
      "Open roles on macro, markets, and policy projects — data collection, writing, and modeling. Each listing names a lead researcher and expected deliverables.",
    emptyProjects:
      "No projects match this filter. Check back as leads publish new roles, or save projects you want to watch.",
    applyMotivation:
      "Why this project? Mention relevant coursework, prior research, or skills (Python, writing, data viz) — leads read every application personally.",
    reviewTitle: "Reviewer dashboard",
    reviewDescription: "Pending applications for projects where you are the lead researcher.",
    reviewAccessDenied: "Reviewer access requires lead_researcher or admin role.",
    reviewEmpty: "No pending applications — members will appear here when they apply to your projects.",
    reviewLoadError: "Could not load the review queue. Try refreshing the page.",
  },
  pathways: {
    eyebrow: "Axiom Pathways",
    title: "Pathways",
    description:
      "Three tracks: paid and volunteer opportunities, studio project showcases, and essay challenges with editorial review.",
    opportunities: {
      eyebrow: "Careers",
      title: "Opportunity board",
      description:
        "Internships, programs, challenges, and project roles from partner organizations. Save roles to revisit later.",
      empty: "No opportunities match your filters. Try another type or check back as partners publish new roles.",
    },
    studios: {
      eyebrow: "Creative",
      title: "Finance Studios",
      description:
        "Student-built finance projects — repos, demos, models, and design sprints shared for feedback and inspiration.",
      empty: "No studio submissions yet. Share a repo, demo, or writeup to add the first entry.",
    },
    essays: {
      eyebrow: "Editorial",
      title: "Financial Takes Challenge",
      description:
        "Submit opinion and market analysis. Community upvotes surface strong writing for editorial review and chapter showcases.",
      empty: "No essays yet. Submit the first take on markets, policy, or investing.",
    },
    hubCtaTitle: "Browse opportunities",
    hubCtaDescription: "Filter by type, organization, or tag — and save roles you want to apply to later.",
    emptyOpportunities:
      "No opportunities listed yet. Ask your chapter lead about partner programs, or check back soon.",
    emptyStudios: "Be the first to submit a studio project.",
    emptyEssays: "Submit your first essay challenge entry.",
  },
  events: {
    eyebrow: "Chapters",
    title: "Events & chapters",
    description:
      "Chapter meetups, speaker series, and workshops worldwide. Register interest for reminders; external links open partner signup pages.",
    emptyEvents:
      "No events scheduled for this chapter yet. Select another chapter on the map, or register for events elsewhere.",
    emptyChapters:
      "Chapters are being added to the directory. Check back soon, or ask your chapter lead about registration.",
  },
  network: {
    eyebrow: "Member network",
    title: "Network",
    description:
      "Browse members by chapter and interest. Send connection requests and post introductions when you're looking for collaborators, mentors, or co-authors.",
    emptyMembers:
      "No members match your filters. Clear the chapter filter or search with a broader interest tag.",
    introFeed: "Introductions feed",
    introEmptyTitle: "No introductions yet",
    introEmptyBody: "Post what you're looking for — collaborators, mentors, or co-authors for a project.",
    postIntro: "Post introduction",
    introDialogTitle: "Introduction",
    introHeadline: "Headline",
    introLookingFor: "What are you looking for?",
    membersSection: "Members",
    searchPlaceholder: "Search by name or interest…",
    profileVisibility: "Your profile visibility",
    openToCollaborateHint: "Let others know you're open to collaborate",
    pendingRequests: "Pending requests",
    accept: "Accept",
    decline: "Decline",
    connectDialogTitle: "Send connection request",
    connectPlaceholder: "Optional note — mention a shared interest or project idea",
    sendRequest: "Send request",
    sending: "Sending…",
    card: {
      sharedInterests: "{count} shared interest",
      sharedInterestsPlural: "{count} shared interests",
      openToCollaborate: "Open to collaborate",
      connect: "Connect",
      sending: "Sending…",
      pending: "Request pending",
      connected: "Connected",
    },
  },
  memberProfile: {
    notFound: "This member profile could not be found or may have been removed.",
    noBio: "No bio added yet.",
    sharedInterestsTitle: "Shared interests",
    sharedInterestsHint:
      "You both follow these topics — a good starting point for a research collaboration or introduction.",
    connectPrompt: "Send a connection request to start a conversation across chapters.",
    badgesTitle: "Membership badges",
    backToNetwork: "Back to network",
    sendConnect: "Send connection request",
    editProfile: "Edit your profile",
    connectionsLabel: "Connections",
    chapterCity: "Chapter city",
  },
  education: {
    eyebrow: "Catalyst",
    title: "Education",
    description:
      "Structured curriculum for outreach and self-study: budgeting, markets, research writing, and glossary terms linked to Debriefed explainers. Progress saves on this device.",
    certificate:
      "All Catalyst lessons complete on this device. Consider applying to a lab project or submitting an essay on Pathways.",
    lessonNotFound: "This lesson could not be found. Return to the education hub to browse modules.",
    exerciseTitle: "Exercise",
    markComplete: "Mark lesson complete",
    markUndo: "Completed — click to undo",
    relatedExplainers: "Related explainers",
    progressNote: "Progress saves locally on this device. Complete all lessons to earn the Catalyst certificate.",
  },
  resources: {
    eyebrow: "Member library",
    title: "Resources",
    description:
      "Facilitator guides, journal submission standards, club toolkits, and partner programs — written for chapter volunteers running events on the ground.",
    guideNotFound: "This guide could not be found. Browse the resource library for facilitator materials.",
    searchPlaceholder: "Search guides, tags, webinars…",
    sections: {
      guides: "Written guides",
      webinars: "Recurring sessions",
      portal: "In the portal",
      external: "External",
    },
    readGuide: "Read guide →",
  },
  saved: {
    eyebrow: "Your library",
    title: "Saved items",
    description:
      "Articles from Debriefed, Meta Labs projects, and Pathways opportunities you've bookmarked.",
    empty:
      "Nothing saved yet. Bookmark from Debriefed, Meta Labs, or Pathways to build your shortlist.",
    discoveryTitle: "Where to save from",
    saveMoreTitle: "Save more",
  },
  activity: {
    eyebrow: "Your feed",
    title: "Activity",
    description:
      "Connections, saved articles, lab applications, and event registrations — filter by type or open any item to continue.",
    empty:
      "No activity in this category yet. Saves, applications, and connections appear here as you use the portal.",
    filterAll: "Everything you've saved, applied to, registered for, and connected with — grouped by day.",
  },
  settings: {
    eyebrow: "Your account",
    title: "Settings",
    description:
      "Your profile drives recommendations across Debriefed, Meta Labs, Pathways, and the member network. Interests are the strongest signal.",
    digestNote: "Weekly digest delivery is rolling out chapter by chapter.",
    securityAdmin:
      "Admin: run migrations 003, 005, 006, and 007 in Supabase if bookmarks, notifications, contact inbox, or education progress fail.",
    securityMember:
      "If Saved items or notifications aren't working, contact your chapter lead — the workspace may need a one-time setup.",
    profileStrength: "Profile strength",
    profileCompleteness: "Profile completeness",
    saving: "Saving…",
    saveChanges: "Save changes",
    openToCollaborate: "Open to collaborate",
    openToCollaborateHint: "Shown on your public profile",
    communications: "Communications",
    weeklyDigest: "Weekly Debriefed digest",
    substackSubscriber: "Substack subscriber",
    changePassword: "Change password",
    updatePassword: "Update password",
    membershipBadges: "Membership badges",
    replayTour: "Replay portal tour",
    resetViaEmail: "Reset via email",
    profileUpdated: "Profile updated",
    passwordsMismatch: "Passwords do not match",
  },
  admin: {
    eyebrow: "Administration",
    title: "Content management",
    description:
      "Publish news, opportunities, events, and explainers for your chapter and the global network.",
    emptyNews: "No articles published yet. Use the form above to add your first Debriefed story.",
    emptyOpportunities: "No opportunities listed. Add internships, programs, or project roles for members.",
    emptyEvents: "No events scheduled. Create a chapter meetup or speaker session above.",
    emptyExplainers: "No explainers published. Add beginner-friendly cards for the Explain This library.",
    emptyChapters: "No chapters yet. Add your first geographic chapter above.",
    emptyInbox: "No contact messages yet.",
    loadError: "Could not load admin content. Check your connection and try again.",
    memberRoleUpdated: "Member role updated.",
    forms: {
      publishArticle: "Publish article",
      editOpportunity: "Edit opportunity",
      addChapter: "Add chapter",
      publish: "Publish",
      save: "Save",
      delete: "Delete",
    },
    toast: {
      articlePublished: "Article published",
      deleted: "Deleted",
      failed: "Could not save changes. Try again.",
    },
  },
  auth: {
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your Finance4All member account.",
    signupTitle: "Join Finance4All",
    signupSubtitle:
      "Create a free member account. One login for news, curriculum, labs, pathways, events, and the member network.",
    emailConfirmTitle: "Check your email",
    emailConfirmBody:
      "We sent a confirmation link. Click it to activate your account, then return here to sign in.",
    onboardingTitle: "Complete your profile",
    onboardingSubtitle:
      "A few details help us surface relevant news, lab openings, and members in your chapter and across the network.",
    onboardingFooter: "You can update your profile anytime in Settings.",
    onboardingGoogleNote: "Your photo will appear on your profile",
    securityFooter: "Finance4All never asks for your password by email. Use a unique password for this account.",
    forgotPasswordTitle: "Reset password",
    forgotPasswordSubtitle: "We'll email you a link to set a new password.",
    forgotPasswordSent: "If an account exists for that email, check your inbox for a reset link.",
    resetPasswordTitle: "Set new password",
    resetPasswordSubtitle: "Choose a strong password for your Finance4All account.",
    resetPasswordSuccess: "Password updated. Sign in with your new password.",
    resetPasswordVerifying: "Verifying reset link…",
    backToSite: "← Back to site",
    portalLabel: "Member Portal",
    backToSignIn: "Back to sign in",
    signOut: "Sign out",
    securingSession: "Securing your session…",
    googleButton: "Continue with Google",
    redirecting: "Redirecting…",
    orDivider: "or",
    signInButton: "Sign in with email",
    signingIn: "Signing in…",
    loginFooter: "No account?",
    loginFooterLink: "Create one",
    forgotLink: "Forgot password?",
    signupFooter: "Already have an account?",
    signupFooterLink: "Sign in",
    createButton: "Create account with email",
    creatingAccount: "Creating account…",
    accountCreated: "Account created! Redirecting…",
    displayNameLabel: "Display name",
    emailLabel: "Email",
    passwordLabel: "Password",
    newPasswordLabel: "New password",
    confirmPasswordLabel: "Confirm password",
    sendResetLink: "Send reset link",
    updatePasswordButton: "Update password",
    enterPortal: "Enter portal",
    signedInWithGoogle: "Signed in with Google",
    supabaseWarningTitle: "Supabase not connected",
    supabaseWarningBody: "Copy .env.example to .env and add your anon key.",
    sidebarTagline: "One login for news, curriculum, labs, pathways, events, and the member network.",
    modules: [
      { name: "Debriefed", desc: "Macro news and explainers" },
      { name: "Meta Labs", desc: "Open research roles" },
      { name: "Pathways", desc: "Opportunities and essays" },
      { name: "Network", desc: "Chapters and introductions" },
    ],
  },
  personalized: {
    title: "For you",
    noInterestsTitle: "Add interests to personalize",
    noInterests:
      "Add interests in Settings — we'll surface news, labs, opportunities, events, and members that match what you care about.",
    learning:
      "Recommendations improve as you explore. Read Debriefed and browse Meta Labs — picks will appear as content grows.",
    suggestedEmpty:
      "Add interests in Settings to see members with overlapping focus areas who are open to connect.",
    loadError: "Could not load personalized picks. Try refreshing the page.",
    suggestedLoadError: "Could not load member suggestions right now.",
    addInterestsCta: "Add interests",
    basedOn: "Based on {interests}",
    suggestedTitle: "Suggested connections",
    updateInterestsCta: "Update interests",
    reasonNewsTag: "Matches your interest in {tag}",
    reasonLab: "Open lab · matches {tag}",
    reasonOpp: "Opportunity · matches {tag}",
    reasonMember: "{count} shared interest",
    reasonMemberPlural: "{count} shared interests",
    reasonEventChapter: "Upcoming at your chapter",
    reasonEvent: "Upcoming chapter event",
    reasonExplainer: "Explainer · {tag}",
    reasonLesson: "Catalyst lesson · {tag}",
  },
  security: {
    sessionWarning:
      "For your security, sign out on shared devices. Finance4All never asks for your password by email.",
    passwordHints:
      "Use at least 8 characters with letters and numbers. Avoid reusing passwords from other sites.",
    twoFactorNote:
      "Two-factor authentication is managed through your account provider. Google sign-in is available for faster access.",
    neverShare: "Never share your password. Sign out on shared devices.",
    rateLimit: "Too many sign-in attempts. Please wait a few minutes before trying again.",
    invalidEmail: "Enter a valid email address.",
    passwordTooShort: "Password must be at least 8 characters with letters and numbers.",
    disposableEmail: "Please use a school or personal email — temporary inboxes aren't accepted.",
    honeypotTriggered: "Something went wrong. Please try again.",
    accessDeniedTitle: "Access restricted",
    accessDeniedBody: "This area is limited to specific member roles. Contact your chapter lead if you believe you should have access.",
    accessDeniedElevated: "This page requires elevated access",
    backToDashboard: "Back to dashboard",
    accountSettings: "Account settings",
    idleTitle: "Still there?",
    continueSession: "Continue session",
    signOutButton: "Sign out",
  },
  search: {
    placeholder: "Search news, labs, opportunities, events, members…",
    emptyHint: "Type at least 2 characters, or try a suggested query below.",
    recentTitle: "Recent searches",
    suggestedTitle: "Try searching for",
    suggestedQueries: [
      "macro research",
      "IPO explainers",
      "open labs",
      "chapter events",
      "network members",
    ],
    trigger: "Search…",
    searching: "Searching…",
    noResults: "No results found.",
    typeLabels: {
      news: "News",
      labs: "Labs",
      opportunities: "Opportunities",
      events: "Events",
      members: "Members",
      explainers: "Explainers",
      lessons: "Lessons",
    },
  },
  shortcuts: {
    title: "Keyboard shortcuts",
    description: "Navigate the portal without reaching for the mouse.",
    search: "Open global search",
    help: "Show this shortcuts panel",
    nav: "Use the sidebar or mobile tabs to jump between modules.",
    escape: "Close dialogs and panels",
  },
  goals: {
    title: "This week",
    description: "Three optional actions — resets every Monday. Skip any you have already done.",
    saveArticle: "Save a Debriefed article",
    connectMember: "Send a connection request",
    completeLesson: "Finish a Catalyst lesson",
    allDone: "You completed all three actions this week.",
    progress: "Still on the list for this week.",
  },
  footer: {
    tagline: "Finance4All — student-run finance education and research network.",
    settings: "Settings",
    saved: "Saved items",
    activity: "Activity feed",
    site: "Public site",
    securityNote: "Never share your password. Sign out on shared devices.",
  },
  landing: {
    heroBadge: "Free membership",
    heroBadgeModules: "Portal · Labs · Chapters · Journal",
    heroTitle: "A global network for",
    heroTitleAccent: "finance education and research.",
    heroSubtext:
      "Finance4All runs chapter workshops, a member portal, mentor-reviewed research, and a student writing pipeline. Free to join — built for students who want to learn markets by doing, not by watching.",
    heroCtaPrimary: "Create free account",
    heroCtaSecondary: "Sign in to portal",
    heroScrollHint: "What we build",
    heroPortalPreview: "Member portal preview",
    heroPortalFooter: "News, research, pathways, and chapter events — one dashboard",
    aboutSubtext:
      "Chapter outreach, mentor-led research, and editorial review share one portal — so a first budgeting lesson can lead to a published macro note.",
    programsSubtext:
      "Each program below opens a live portal module: Catalyst lessons, lab applications, Pathways submissions, or facilitator guides your chapter can run this month.",
    ecosystemEyebrow: "Member portal",
    ecosystemTitle: "What's in the portal",
    ecosystemDescription:
      "Each card opens a live module — news, labs, pathways, network, education, resources, and events.",
    testimonialsEyebrow: "From members",
    testimonialsTitle: "What members say",
    impactEyebrow: "Outcomes",
    impactTitle: "Where members spend their time",
    impactAside:
      "Each track links to a live portal module — not a brochure page.",
    resourcesEyebrow: "Write & learn",
    resourcesTitle: "Curriculum, journal, and chapter tools",
    resourcesBody:
      "Lesson library, submission standards, podcasts, and club playbooks — the same materials chapter volunteers use on the ground.",
    resourcesCta: "Create free account",
    membershipTitle: "Free access. Real modules.",
    membershipDescription:
      "No tiered paywall. One account opens Debriefed, Education, Labs, Pathways, Network, Resources, and your chapter calendar.",
    ctaEyebrow: "Get started",
    ctaTitle: "Join free — no membership fee",
    ctaBody:
      "One account for news, curriculum, lab applications, chapter events, and the member directory.",
    contactEyebrow: "Get in touch",
    contactTitle: "Questions, submissions, or chapter inquiries",
    contactBody:
      "Send journal drafts, lab project ideas, chapter launch questions, or general inquiries. We read every message.",
    contactSubmit: "General inquiries & submissions",
    contactFounder: "Founder & partnerships",
    contactSend: "Send message",
    contactSuccess: "Message received — we'll get back to you soon.",
    contactSuccessDetail: "You can also reach us directly via the email links below.",
    contactError: "Could not send your message. Try again or email us directly.",
    founderEyebrow: "Leadership",
    founderTitle: "The team behind Finance4All",
    founderSubtext:
      "Students and recent graduates who run outreach, build curriculum, and review research — not a distant advisory board.",
    footerTagline: "Student-run finance education and research network.",
    footerMission: "Outreach, curriculum, and research — free for every student.",
    socialProofLabel: "Programs inside Finance4All",
    documentTitle: "Student-run finance education and research network",
    skipToContent: "Skip to content",
    contactSending: "Sending…",
    contactSendAnother: "Send another message",
    contactLabels: {
      name: "Name",
      email: "Email",
      subject: "Subject",
      message: "Message",
    },
    contactPlaceholders: {
      name: "Your name",
      email: "you@school.edu",
      subject: "Chapter inquiry, submission, partnership…",
      message: "How can we help?",
    },
  },
  discovery: {
    title: "Where to go next",
    debriefed: {
      title: "Read Debriefed",
      description: "Macro, markets, and IPO coverage from your chapter feed.",
    },
    labs: {
      title: "Browse Meta Labs",
      description: "Open research roles — each listing names a lead and expected deliverables.",
    },
    network: {
      title: "Open Network",
      description: "Find members in your chapter or post an introduction.",
    },
    events: {
      title: "Chapter events",
      description: "RSVP to meetups and workshops — at your chapter or elsewhere.",
    },
    savedDebriefed: {
      title: "Debriefed articles",
      description: "Save articles while reading to build a shortlist here.",
    },
    savedLabs: {
      title: "Lab projects",
      description: "Bookmark projects you want to apply to later.",
    },
    savedPathways: {
      title: "Pathways roles",
      description: "Save internships and programs from the opportunity board.",
    },
  },
  onboarding: {
    eyebrow: "First steps",
    title: "Set up your account",
    steps: {
      profile: "Add your bio, interests, and chapter in Settings",
      debriefed: "Read one article on Debriefed",
      education: "Complete one Catalyst lesson",
      network: "Send a connection request on Network",
      saved: "Save an article or lab project",
    },
    ctaProfile: "Open Settings",
    ctaExplore: "Browse Network",
  },
  tour: {
    step1Title: "Your member dashboard",
    step1Body: "The dashboard surfaces articles, lab openings, events, and members based on your interests and chapter.",
    step2Title: "Search the portal",
    step2Body: "Press ⌘K (Ctrl+K on Windows) to search articles, labs, opportunities, events, and members from any page.",
    step3Title: "Complete your profile",
    step3Body: "Bio, interests, and chapter drive what appears in your feed and in member search results.",
    step3Cta: "Go to Settings",
    step4Title: "Choose a starting point",
    step4Body: "Debriefed for news, Meta Labs for research roles, Network for chapter members — pick what fits your week.",
    step4Cta: "Open Debriefed",
    finish: "Done",
    next: "Next",
    back: "Back",
  },
  glossary: {
    title: "Term search",
    description: "Search explainers and lesson key terms — results link to the source page.",
    placeholder: "e.g. IPO, inflation, diversification…",
    empty: "No matches for that term.",
    explainersLink: "all explainers",
    educationLink: "education hub",
  },
  ui: {
    loading: "Loading…",
    emptyDefault: "Nothing here yet.",
    errorDefault: "Could not load this section. Try refreshing the page.",
    retry: "Try again",
  },
  educationHub: {
    progress: "lessons completed",
    completeTitle: "Catalyst track complete",
    completeToast: "You finished every Catalyst lesson on this device.",
    facilitatorLink: "Facilitator resources",
  },
  dashboardSections: {
    flagship: "Programs",
    modules: "All modules",
    recentActivity: "Recent activity",
    debriefed: "Latest from Debriefed",
  },
  labTracker: {
    title: "Your lab applications",
    empty: "No applications yet. Browse open Meta Labs projects — most take about five minutes to apply.",
    status: {
      pending: "Submitted — the lead researcher will review your application.",
      under_review: "Under review — check back soon or save other projects while you wait.",
      accepted: "Accepted — the lead will reach out with next steps.",
      rejected: "Not selected this round — explore other open projects.",
    },
    viewProject: "View project",
    browseLabs: "Browse labs",
    fallbackTitle: "Research project",
    submitted: "Submitted {date}",
  },
  calendar: {
    addToCalendar: "Add to calendar",
    downloadHint: "Downloads an .ics file for Apple Calendar, Google Calendar, or Outlook.",
  },
  memberActivity: {
    title: "Member snapshot",
    openToCollaborate: "Open to collaborate on research and projects",
    chapterMember: "Chapter member",
    connections: "connections across the network",
    memberSince: "Member since",
    viewNetwork: "Browse the network",
    readingProgress: "Catalyst lessons completed on this device",
  },
  breadcrumbs: {
    dashboard: "Dashboard",
    education: "Education",
    lesson: "Lesson",
    network: "Network",
    profile: "Member profile",
    resources: "Resources",
    guide: "Guide",
    labs: "Meta Labs",
    project: "Project",
    debriefed: "Debriefed",
    explainers: "Explainers",
    explainer: "Explainer",
  },
  layout: {
    memberPortal: "Member Portal",
    backToSite: "← Site",
    signOut: "Sign out",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    documentTitle: "Portal",
  },
  nav: {
    mobile: {
      home: "Home",
      news: "News",
      learn: "Learn",
      labs: "Labs",
      network: "Network",
      more: "More",
      moreTitle: "More modules",
    },
  },
  interests: {
    yourFocus: "Your focus",
    theirFocus: "Their focus",
    personalize: "Add interests in Settings to personalize your feed",
  },
  communityPulse: {
    members: "Members",
    chapters: "Chapters",
    openLabs: "Open labs",
    introductions: "Introductions",
    error: "Community stats are temporarily unavailable.",
    retry: "Retry",
  },
  pathwaysUi: {
    submitStudios: "Submit to Studios",
    submitProject: "Submit project",
    submitEssay: "Submit essay",
    submitTake: "Submit your take",
    editorialPick: "Editorial pick",
    publish: "Publish",
    searchOpportunities: "Search opportunities…",
    saved: "Saved",
    save: "Save",
    apply: "Apply",
  },
} as const;
