import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useAuth } from '@/contexts/useAuth';
import { useResearchProjects } from '@/hooks/portal/useLabs';
import { useCollaboration } from '@/hooks/portal/useCollaboration';
import { PortalCard,PortalPageHeader,QueryStatus } from '@/components/portal/PortalUI';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import type { Tables } from '@/types/database';
function Task({task,canEdit,manager,onSave,pending}:{task:Tables<'project_tasks'>;canEdit:boolean;manager:boolean;onSave:(v:{id:string;revision:number;status:Tables<'project_tasks'>['status'];evidence_url:string})=>Promise<unknown>;pending:boolean}){
 const [status,setStatus]=useState(task.status),[evidence,setEvidence]=useState(task.evidence_url),[error,setError]=useState('');
 return <PortalCard className="space-y-3 p-5"><p className="text-xs uppercase">{task.kind} · {task.status.replaceAll('_',' ')}</p><h3 className="font-semibold text-lg">{task.title}</h3><p>{task.description}</p><p>Due: {task.due_date??'No deadline'} · Assigned account: {task.assignee_id??'Unassigned'}</p>{task.evidence_url&&<a href={task.evidence_url} target="_blank" rel="noopener noreferrer" className="underline">Open submitted evidence</a>}{canEdit&&<form className="space-y-3" onSubmit={async e=>{e.preventDefault();setError('');try{await onSave({id:task.id,revision:task.revision,status,evidence_url:evidence});}catch(err){setError(err instanceof Error?err.message:'Task update failed.');}}}><label className="block">Status<select className="block w-full border rounded-md bg-background p-3" value={status} onChange={e=>setStatus(e.target.value as typeof status)}>{['todo','in_progress','submitted',...(manager?['done']:[])].map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></label><label className="block">HTTPS evidence link<Input type="url" maxLength={1000} value={evidence} onChange={e=>setEvidence(e.target.value)} required={status==='submitted'||status==='done'}/></label><Button type="submit" disabled={pending}>Save task</Button></form>}{error&&<p role="alert">{error}</p>}</PortalCard>;
}
export default function Collaboration(){
 const {user,profile}=useAuth();const [params,setParams]=useSearchParams();const projectId=params.get('project')??'';const projects=useResearchProjects();const work=useCollaboration(projectId);
 const [member,setMember]=useState(''),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[assignee,setAssignee]=useState(''),[due,setDue]=useState(''),[kind,setKind]=useState<'task'|'milestone'>('task'),[error,setError]=useState(''),[message,setMessage]=useState('');
 const project=projects.data?.find(p=>p.id===projectId);const manager=Boolean(project&&(project.leadResearcherId===user?.id||profile?.role==='admin'));const active=Boolean(manager||work.memberships.data?.some(m=>m.project_id===projectId&&m.user_id===user?.id&&m.status==='active'));
 async function action(fn:()=>Promise<unknown>,success:string){setError('');setMessage('');try{await fn();setMessage(success);}catch(e){setError(e instanceof Error?e.message:'The action could not be confirmed. Refresh before retrying.');}}
 return <div className="space-y-6"><PortalPageHeader title="Project collaboration" description="Accept a project invitation, agree the work and attach evidence to deliverables. Only the project lead or an administrator can accept completed work."/><QueryStatus isLoading={projects.isLoading} error={projects.error} onRetry={()=>void projects.refetch()}><label className="block">Project<select className="block w-full border rounded-md bg-background p-3" value={projectId} onChange={e=>{setParams(e.target.value?{project:e.target.value}:{});setAssignee('');setTitle('');setDescription('');setError('');setMessage('');}}><option value="">Choose a project or review your invitations</option>{projects.data?.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></QueryStatus>
 <QueryStatus isLoading={work.memberships.isLoading} error={work.memberships.error} onRetry={()=>void work.memberships.refetch()}><section className="space-y-3"><h2 className="font-semibold text-xl">Memberships & invitations</h2>{!work.memberships.data?.length&&<p>No invitations or memberships are visible in this view.</p>}{work.memberships.data?.map(m=><PortalCard className="p-4 space-y-2" key={m.project_id+m.user_id}><p>{projects.data?.find(p=>p.id===m.project_id)?.title??'Project invitation'} · {m.status}</p><p className="break-all text-sm">Member account: {m.user_id}</p><div className="flex flex-wrap gap-2">{m.user_id===user?.id&&m.status==='invited'&&(['active','declined'] as const).map(status=><Button key={status} type="button" disabled={work.respond.isPending} onClick={()=>void action(()=>work.respond.mutateAsync({...m,status,previous:m.status}),status==='active'?'Invitation accepted.':'Invitation declined.')}>{status==='active'?'Accept invitation':'Decline'}</Button>)}{m.user_id===user?.id&&m.status==='active'&&<Button type="button" variant="outline" disabled={work.respond.isPending} onClick={()=>{if(window.confirm('Leave this project? Access to its private tasks will end.'))void action(()=>work.respond.mutateAsync({...m,status:'left',previous:m.status}),'You have left the project.');}}>Leave project</Button>}{manager&&m.status!=='removed'&&<Button type="button" variant="outline" disabled={work.respond.isPending} onClick={()=>{if(window.confirm('Remove this member’s access?'))void action(()=>work.respond.mutateAsync({...m,status:'removed',previous:m.status}),'Project access removed.');}}>Remove access</Button>}{manager&&['left','declined','removed'].includes(m.status)&&<Button type="button" variant="outline" disabled={work.respond.isPending} onClick={()=>void action(()=>work.respond.mutateAsync({...m,status:'invited',previous:m.status}),'New invitation recorded.')}>Invite again</Button>}</div></PortalCard>)}</section></QueryStatus>
 {manager&&<PortalCard className="p-5"><form className="space-y-3" onSubmit={e=>{e.preventDefault();void action(()=>work.invite.mutateAsync(member.trim()),'Invitation recorded. The member must accept before accessing tasks.');}}><h2 className="text-xl font-semibold">Invite a member</h2><label className="block">Member account ID<Input required value={member} onChange={e=>setMember(e.target.value)} pattern="[0-9a-fA-F-]{36}"/></label><p className="text-sm">Use the account ID from the member’s profile URL. Invitations are visible in their collaboration workspace.</p><Button type="submit" disabled={work.invite.isPending}>Create invitation</Button></form></PortalCard>}
 {manager&&<PortalCard className="p-5"><form className="space-y-3" onSubmit={e=>{e.preventDefault();void action(async()=>{await work.createTask.mutateAsync({project_id:projectId,title:title.trim(),description,assignee_id:assignee||null,due_date:due||null,kind});setTitle('');setDescription('');},'Work item created.');}}><h2 className="text-xl font-semibold">Define work</h2><label className="block">Title<Input required minLength={3} maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="block">Description<Input maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="block">Kind<select className="block border bg-background p-3" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="task">Task</option><option value="milestone">Milestone</option></select></label><label className="block">Assign to<select className="block w-full border bg-background p-3" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option><option value={project?.leadResearcherId}>Project lead</option>{work.memberships.data?.filter(m=>m.status==='active'&&m.user_id!==project?.leadResearcherId).map(m=><option key={m.user_id} value={m.user_id}>{m.user_id}</option>)}</select></label><label className="block">Due date<Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><Button type="submit" disabled={work.createTask.isPending}>Create work item</Button></form></PortalCard>}
 {projectId&&<section className="space-y-4"><h2 className="text-xl font-semibold">Tasks & milestones</h2><QueryStatus isLoading={work.tasks.isLoading} error={work.tasks.error} onRetry={()=>void work.tasks.refetch()}>{!work.tasks.data?.length&&<p>{active?'No work items have been created.':'No private tasks are visible. Project participation requires an accepted invitation.'}</p>}{work.tasks.data?.map(task=><Task key={`${task.id}-${task.revision}`} task={task} manager={manager} canEdit={manager||(active&&task.assignee_id===user?.id&&task.status!=='done')} onSave={work.updateTask.mutateAsync} pending={work.updateTask.isPending}/>)}</QueryStatus></section>}{error&&<p role="alert">{error}</p>}<p role="status">{message}</p></div>;
}
