import { useState } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpenText, FlaskConical, Globe2, HeartHandshake, Mail, Menu, Pause, Play, Users, X } from "lucide-react";
import { Link } from "react-router-dom";
import Brand from "@/components/Brand";
import ThemeToggle from "@/components/ThemeToggle";
import { BoxReveal, ContainerScroll, EncryptedText, Lens, MediaText, MorphingTabs, NeuralBackground } from "@/components/experience/Interactions";
import WorldMap, { WorldOutline } from "@/components/experience/WorldMap";
import { affiliations, communityLocations, plannedPrograms } from "@/content/community";
import { featuredExplainers } from "@/content/editorial";
import { useDocumentTitle } from "@/hooks/useDocumentTitle";
import "@/styles/landing.css";

const programs = [
  { title: "Student school visits", tag: "In the classroom", description: "Practical, approachable sessions that bring money, markets, and economic decisions into the classroom. Start with everyday questions, build confidence, and give students a place to ask more.", action: "Bring us to your school", href: "https://tally.so/r/q4rlKd" },
  { title: "Global school clubs", tag: "Student-led", description: "A home for curious students at their own school. Run discussions, explore current events, teach a lesson, and build a local community connected to a global network.", action: "Start a chapter", href: "https://tally.so/r/XxaB1j" },
  { title: "Live industry projects", tag: "Learn by doing", description: "Bring classroom ideas into real problems. Explore company research, economic analysis, and projects shaped with people working in industry.", action: "Explore project pathways", to: "/portal/pathways/studios" },
  { title: "Economics Olympiad", tag: "Think beyond the syllabus", description: "Build intuition, practise economic reasoning, and connect with a wider competition community, including our work with the USA Economics Olympiad.", action: "Ask about the Olympiad", href: "mailto:financeforalledu@gmail.com?subject=Economics%20Olympiad" },
  { title: "Digital education", tag: "Open learning", description: "Learn at your own pace with practical foundations and long-form explainers. No finance background needed: just curiosity and a question you want answered.", action: "Take the open lesson", to: "/learn/five-foundations" },
  { title: "Global university outreach", tag: "Across campuses", description: "Connect students across schools and universities through conversations, research, and shared projects. Different starting points. A much wider world of ideas.", action: "Connect your campus", href: "mailto:financeforalledu@gmail.com?subject=University%20outreach" },
];
const research = [
  { name: "FI-JEPA", field: "Financial machine learning", question: "Can models learn useful market representations without simply chasing the next price?", href: "https://github.com/Finance-Meta-Research/FI-JEPA" },
  { name: "Eigen-JEPA", field: "Market structure & systemic risk", question: "What can changing correlations and market geometry tell us about financial regimes?", href: "https://github.com/Finance-Meta-Research/Eigen-JEPA" },
  { name: "EigenFinance", field: "Portfolio evaluation", question: "How do portfolio strategies compare when timing, holdouts, and transaction costs are treated carefully?", href: "https://github.com/Finance-Meta-Research/EigenFinance" },
  { name: "LGWM", field: "Liquidation Graph World Models", question: "How can leverage, liquidity, and connected institutions turn a local shock into a wider crisis?" },
  { name: "Finimmunity", field: "Financial resilience & recovery", question: "How do markets adapt to shocks—and when do their responses create persistent feedback loops?" },
];

function Notebook() {
  return <div className="research-notebook"><div><span>Finance Meta Labs</span><span>Research notebook / 01</span></div><h3>A better question<br />changes everything.</h3><p>How does financial stress travel?</p><svg viewBox="0 0 400 160" role="img" aria-label="Conceptual network linking lenders, funds, assets, and households"><g stroke="#799382" strokeWidth="1.5"><path d="M55 80 155 30 250 85 345 35M55 80 160 135 250 85 345 130M155 30 160 135M345 35 345 130" /></g>{[[55,80,"Lenders"],[155,30,"Funds"],[160,135,"Assets"],[250,85,"Liquidity"],[345,35,"Firms"],[345,130,"Households"]].map(([x,y,label]) => <g key={label}><circle cx={x} cy={y} r="7" fill="#264b3a" /><text x={x} y={Number(y)+20} textAnchor="middle" fontSize="11" fill="#264b3a">{label}</text></g>)}</svg><div className="notebook-notes"><span>Ask a question</span><span>Explore the data</span><span>Share what you learn</span></div><small>Conceptual illustration · not an empirical result</small></div>;
}

function PortalPreview({ kind }: { kind: "Learn" | "Research" | "Connect" }) {
  const items = kind === "Learn" ? ["Understand an IPO, from prospectus to first trade", "How inflation changes purchasing power", "Interest, borrowing, and the cost of money"] : kind === "Research" ? ["Explore Finance Meta Labs", "Read a project brief and choose your question", "Apply, collaborate, and submit your work"] : ["Find students with shared interests", "Start a school club or run a session", "Discover opportunities through Axiom Pathways"];
  const Icon = kind === "Learn" ? BookOpenText : kind === "Research" ? FlaskConical : Users;
  return <div className="membership-preview"><div className="preview-sidebar"><Brand /><span>Your member space</span>{["Overview", "Finance Debriefed", "Finance Meta Labs", "Opportunities", "Community", "Saved"].map(label => <span key={label}>{label}</span>)}</div><div className="preview-main"><p className="ffa-eyebrow">A look inside</p><h3>Your next idea<br />starts here.</h3><p>One space to learn, contribute, and meet the people building alongside you.</p><div className="preview-feature"><Icon size={26} /><span>{kind === "Learn" ? "Go beyond the headline." : kind === "Research" ? "Follow your curiosity." : "Find your people."}</span></div>{items.map((item,i) => <div className="preview-row" key={item}><span>0{i + 1}</span>{item}<ArrowUpRight size={16} /></div>)}<Link to="/signup" className="ffa-text-link">Make it yours <ArrowRight size={16} /></Link></div></div>;
}

export default function Index() {
  useDocumentTitle("Financial literacy without barriers");
  const [menuOpen, setMenuOpen] = useState(false);
  const [marqueePaused, setMarqueePaused] = useState(false);
  return <div className="ffa-home">
    <a href="#main-content" className="ffa-skip">Skip to content</a>
    <header className="ffa-header"><Link to="/" aria-label="Finance for All home"><Brand /></Link><nav aria-label="Main navigation" className={menuOpen ? "is-open" : ""}><a href="#purpose" onClick={() => setMenuOpen(false)}>Our story</a><a href="#programs" onClick={() => setMenuOpen(false)}>Programs</a><a href="#research" onClick={() => setMenuOpen(false)}>Research</a><a href="#community" onClick={() => setMenuOpen(false)}>Community</a></nav><div className="ffa-header-actions"><ThemeToggle /><Link to="/login" className="ffa-signin">Sign in</Link><Link to="/signup" className="ffa-button ffa-button-small">Join us <ArrowUpRight size={15} /></Link><button type="button" className="ffa-menu" aria-label={menuOpen ? "Close menu" : "Open menu"} aria-expanded={menuOpen} onClick={() => setMenuOpen(v => !v)}>{menuOpen ? <X /> : <Menu />}</button></div></header>
    <main id="main-content">
      <section className="ffa-hero">
        <NeuralBackground />
        <div className="ffa-hero-top"><p className="ffa-eyebrow"><EncryptedText text="FINANCIAL LITERACY. WITHOUT BARRIERS." /></p><span>Born in Bangalore. Built for the world.</span></div>
        <div className="ffa-hero-grid"><h1><BoxReveal>Money shapes</BoxReveal><br /><BoxReveal delay={120}>every life.</BoxReveal><br /><em><BoxReveal delay={240}>Let's open it up.</BoxReveal></em></h1><div className="ffa-hero-note"><span className="ffa-open-label">An open invitation</span><p>Not just for finance students.<br />Not just for the well-connected.<br /><strong>For all of us.</strong></p><span>Understand the world of money. Ask better questions. Create possibilities for yourself—and for others.</span><div><Link to="/signup" className="ffa-button">Find your place <ArrowUpRight size={18} /></Link><a href="#programs" className="ffa-hero-explore">Explore what we do <ArrowDown size={15} /></a></div></div></div>
        <div className="ffa-metrics"><div><strong>100,000<span>+</span></strong><p>students reached</p></div><div><strong>1M<span>+</span></strong><p>impressions across LinkedIn</p></div><div><strong>6</strong><p>continents. One shared purpose.</p></div><div className="ffa-metrics-note"><Globe2 size={28} /><span>Open minds.<br />A world of possibility.</span></div></div>
        <p className="ffa-metrics-disclosure">Community reach figures are organisation-reported as of September 2026 and have not been independently audited.</p>
      </section>
      <section className="ffa-purpose ffa-section" id="purpose"><p className="ffa-eyebrow">01 / Why we exist</p><div className="ffa-purpose-grid"><h2>Understanding money<br />should never be<br /><em>out of reach.</em></h2><div><p className="ffa-lead">Financial literacy is not a privilege. It is a starting point.</p><p>Money influences the choices we make, the opportunities we find, and the futures we imagine. Yet too many people are left to figure it out alone—with unfamiliar language, limited access, or the feeling that finance is not for them.</p><p>Finance for All exists to change that. We make financial and economic learning accessible through school visits, open lessons, student-led clubs, research, and conversations that welcome everyone.</p><p>Our purpose is simple: remove the barriers between curiosity and understanding. Then give people the community and confidence to do something with what they learn.</p><Link to="/learn/five-foundations" className="ffa-text-link">Start with a free lesson <ArrowRight size={17} /></Link></div></div></section>
      <section className="ffa-history ffa-section"><div className="ffa-section-heading"><div><p className="ffa-eyebrow">Our story, still being written</p><h2>From one city.<br /><MediaText media={<WorldOutline />}>To a wider world.</MediaText></h2></div><p>We started with financial literacy in Bangalore. The question grew with us: what happens when more people have the knowledge, the network, and the space to contribute?</p></div><div className="ffa-timeline">{[
        ["2023", "It starts in Bangalore.", "Finance for All is founded with a simple mission: make financial literacy accessible. School and community learning becomes the starting point."],
        ["Across India", "The conversation grows.", "The initiative expands beyond Bangalore, connecting more students and bringing financial education into more classrooms and communities."],
        ["2025", "Finance Debriefed launches.", "We begin making finance and economics easier to follow through accessible explanations."],
        ["Early 2026", "A new chapter: Finance Meta.", "Finance Meta launches as the home for research and connected projects, taking the community and its ambitions further across the world."],
      ].map(([year,title,copy]) => <article key={year}><span>{year}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="ffa-history-note">Along the way, a student podcast has opened another space for conversations about economics, research, and the people behind the ideas.</p></section>
      <section className="ffa-programs ffa-section" id="programs"><div className="ffa-section-heading"><div><p className="ffa-eyebrow">02 / Our flagship programs</p><h2>Many ways in.<br /><em>Room to go further.</em></h2></div><p>Learn a concept. Lead a classroom. Write an argument. Follow a research question. There is no single way to be part of Finance for All.</p></div>
        <article className="ffa-flagship ffa-labs-flagship"><div><span className="ffa-eyebrow">01 / Flagship · Research</span><h3>Finance Meta Labs</h3><p>A place for people to do economics research—not just read about it. Explore markets, financial systems, public policy, and the questions that connect them. Learn a method, work with others, and develop an idea into something worth sharing.</p><div><a href="#research" className="ffa-button">Meet the labs <ArrowRight size={16} /></a><Link to="/portal/labs" className="ffa-text-link">Enter the workspace</Link></div></div><Lens label="Look closer at the research"><Notebook /></Lens></article>
        <article className="ffa-flagship ffa-journal-flagship"><div className="ffa-journal-cover" aria-hidden="true"><span>Student perspectives.<br />Economic inquiry.</span><strong>IYERN<span>Journal</span></strong><div>Fresh perspectives.<br />Serious questions.</div><small>Economics / Ideas / Inquiry</small></div><div><span className="ffa-eyebrow">02 / Flagship · Economics journal</span><h3>A place for your<br />economic thinking.</h3><p>IYERN brings the economics journal and student research network together. Develop a question, make a thoughtful argument, and learn to communicate it clearly. It is a platform for the next generation to take part in the economic conversation.</p><a href="https://github.com/build-the-future-11/Iy-ERN" target="_blank" rel="noreferrer" className="ffa-text-link">Explore IYERN <ArrowUpRight size={17} /></a><a href="mailto:financeforalledu@gmail.com?subject=IYERN%20submission" className="ffa-text-link">Ask about submitting your work <ArrowRight size={17} /></a></div></article>
        <div className="ffa-program-grid">{programs.map((program,index) => <article key={program.title}><div><span>0{index+3}</span><small>Flagship</small></div><p className="ffa-eyebrow">{program.tag}</p><h3>{program.title}</h3><p>{program.description}</p>{program.to ? <Link to={program.to} className="ffa-text-link">{program.action}<ArrowUpRight size={16} /></Link> : <a href={program.href} className="ffa-text-link" {...(program.href?.startsWith("https") ? { target: "_blank", rel: "noreferrer" } : {})}>{program.action}<ArrowUpRight size={16} /></a>}</article>)}</div>
        <div className="ffa-other-programs"><div><BookOpenText /><h3>Finance Debriefed</h3><p>Finance and economics, unpacked. Find the context behind the headline and the mechanics behind everyday money.</p><Link to="/learn/debriefs">Read the debriefs <ArrowUpRight size={16} /></Link></div><div><HeartHandshake /><h3>Axiom Pathways</h3><p>Discover programs, project roles, internships, and other ways to turn your interests into a next step.</p><Link to="/portal/pathways">Explore pathways <ArrowUpRight size={16} /></Link></div><div><Users /><h3>The student podcast</h3><p>Conversations with people asking questions and building careers across economics, research, and industry.</p><span>Episode library coming soon</span></div></div>
        <details className="ffa-planned"><summary><span><small>The next chapter</small><strong>Nine programs we are developing.</strong></span><span className="ffa-planned-plus" aria-hidden="true">+</span></summary><p>New ideas for extending access and putting learning into practice. These are planned programs; launch details will appear here as they take shape.</p><div>{plannedPrograms.map((p,i) => <article key={p.title}><span>Coming soon / {String(i+1).padStart(2,"0")}</span><h3>{p.title}</h3><p>{p.detail}</p></article>)}</div></details>
      </section>
      <section className="ffa-activities ffa-section"><div className="ffa-section-heading"><div><p className="ffa-eyebrow">03 / Out in the world</p><h2>Built through<br /><em>real collaboration.</em></h2></div><p>Learning gets more interesting when people come together. A few of the collaborations shaping our community.</p></div><div className="ffa-activity-grid"><article><span>Summer program</span><h3>Youth Economy Lab</h3><p>A summer-program collaboration with YEL, bringing our communities together around economics and learning.</p><strong>Finance for All × YEL</strong></article><article><span>Summer program</span><h3>Sintika</h3><p>Working with Sintika on a summer program to create more opportunities for students to learn and participate.</p><strong>Finance for All × Sintika</strong></article><article><span>Finance summit</span><h3>Locked In</h3><p>A summit collaboration featuring speakers with experience at Stanford, MIT, J.P. Morgan, and Citi.</p><strong>Finance for All × Locked In</strong></article></div><div className="ffa-partners"><p>Program partners & collaborators</p><div><span>Youth Economy Lab</span><span>Sintika</span><span>Locked In</span><span>USA Economics Olympiad</span><span>Axiom Pathways</span></div></div></section>
      <section className="ffa-research ffa-section" id="research"><div className="ffa-section-heading"><div><p className="ffa-eyebrow"><EncryptedText text="04 / FINANCE META LABS" /></p><h2>The next question<br />could be <em>yours.</em></h2></div><div><p>From market behaviour to financial access, our research connects economics, data, and ideas. Existing labs stay at the heart of the program, with new directions opening up alongside them.</p><Link to="/portal/labs" className="ffa-text-link">Explore all research <ArrowRight size={16} /></Link></div></div><div className="ffa-research-tracks"><div><span>Lab 01</span><h3>Quantitative Markets<br />& Microstructure</h3><p>Market dynamics, forecasting, portfolio methods, execution, and risk.</p><a href="https://tally.so/r/0Q9qZy" target="_blank" rel="noreferrer">Apply to the lab <ArrowUpRight size={16} /></a></div><div><span>Lab 02</span><h3>Financial Systems,<br />Access & Policy</h3><p>Payments, inclusion, credit, consumer experiences, and economic policy.</p><a href="https://tally.so/r/lbG8Yk" target="_blank" rel="noreferrer">Apply to the lab <ArrowUpRight size={16} /></a></div></div><div className="ffa-research-list">{research.map((project,i) => <article key={project.name}><span>0{i+1}</span><div><small>{project.field}</small><h3>{project.name}</h3></div><p>{project.question}</p>{project.href ? <a href={project.href} aria-label={`Explore ${project.name} repository`} target="_blank" rel="noreferrer"><ArrowUpRight /></a> : <a href={`mailto:financeforalledu@gmail.com?subject=${encodeURIComponent(`${project.name} research`)}`} aria-label={`Ask about ${project.name} research`}><Mail size={21} /></a>}</article>)}</div><p className="ffa-research-note">Research in progress. These are questions and working projects, not claims of investment performance.</p></section>
      <section className="ffa-affiliations"><div><p>Our members, speakers, and project contributors bring experience from</p><button type="button" onClick={() => setMarqueePaused(v => !v)} aria-label={marqueePaused ? "Play affiliation scroll" : "Pause affiliation scroll"}>{marqueePaused ? <Play size={15} /> : <Pause size={15} />}</button></div><div className="ffa-marquee" data-paused={marqueePaused}><div>{[0,1].map(copy => <div className="ffa-marquee-copy" key={copy} aria-hidden={copy === 1}>{affiliations.map(name => <span key={name}>{name}</span>)}</div>)}</div></div><small>Individual affiliations—not institutional endorsements or partnerships.</small></section>
      <section className="ffa-section ffa-community" id="community"><div className="ffa-section-heading"><div><p className="ffa-eyebrow">05 / One connected community</p><h2>Different places.<br /><em>Shared curiosity.</em></h2></div><p>Across six continents, students are finding ways to learn, connect, and contribute. Explore our community locations or take the first step towards a club at your school.</p></div><WorldMap locations={communityLocations} /><div className="ffa-community-bottom"><span>A local starting point. A global conversation.</span><a href="https://tally.so/r/XxaB1j" className="ffa-text-link" target="_blank" rel="noreferrer">Start a school club or chapter <ArrowUpRight size={17} /></a></div></section>
      <section className="ffa-membership ffa-section" id="membership"><div className="ffa-section-heading"><div><p className="ffa-eyebrow">06 / Your member space</p><h2>Come for an answer.<br /><em>Stay for what comes next.</em></h2></div><p>Finance Debriefed, research labs, opportunities, a worldwide student network, and a place to share your work. All connected through your own member profile.</p></div><ContainerScroll><MorphingTabs label="Explore the membership portal" tabs={(["Learn","Research","Connect"] as const).map(kind => ({ label: kind, content: <PortalPreview kind={kind} /> }))} /></ContainerScroll><div className="ffa-member-benefits"><span>Save articles & projects</span><span>Meet students worldwide</span><span>Apply to opportunities</span><span>Share work & ideas</span></div></section>
      <section className="ffa-reading ffa-section" id="debriefs"><div className="ffa-section-heading"><div><p className="ffa-eyebrow">Finance Debriefed</p><h2>Less jargon.<br /><em>More understanding.</em></h2></div><Link to="/learn/debriefs" className="ffa-text-link">Explore the reading room <ArrowRight size={17} /></Link></div><div className="ffa-reading-grid">{featuredExplainers.slice(0,3).map((article,i) => <Link to={`/learn/debriefs/${article.slug}`} key={article.slug}><div className={`ffa-reading-art art-${i}`} aria-hidden="true"><span>{["IPO","%","↗"][i]}</span><small>Finance Debriefed / 0{i+1}</small></div><div><small>{article.difficulty} · {article.readMinutes} min read</small><h3>{article.title}</h3><p>{article.summary}</p><span className="ffa-text-link">Read the full story <ArrowUpRight size={16} /></span></div></Link>)}</div></section>
      <section className="ffa-contact ffa-section" id="contact"><p className="ffa-eyebrow">There is a place for you here.</p><h2><BoxReveal>Bring your questions.</BoxReveal><br /><em><BoxReveal>Leave your mark.</BoxReveal></em></h2><p>Join the community, submit your work, bring a session to your school, or tell us what you would like to build.</p><div><Link to="/signup" className="ffa-button">Become a member <ArrowUpRight size={18} /></Link><a href="mailto:financeforalledu@gmail.com" className="ffa-button ffa-button-outline">Let's talk <Mail size={17} /></a></div><div className="ffa-contact-addresses"><a href="mailto:financeforalledu@gmail.com">financeforalledu@gmail.com</a><a href="mailto:ryangomes.hs@gmail.com">ryangomes.hs@gmail.com</a></div></section>
    </main>
    <footer className="ffa-footer"><div><Brand /><p>Financial literacy for everyone.<br />Founded in Bangalore, 2023.</p></div><div><span>Explore</span><a href="#programs">Our programs</a><a href="#research">Finance Meta Labs</a><Link to="/learn/debriefs">Finance Debriefed</Link></div><div><span>Get involved</span><Link to="/signup">Become a member</Link><a href="https://tally.so/r/XxaB1j" target="_blank" rel="noreferrer">Start a chapter</a><a href="mailto:financeforalledu@gmail.com?subject=Submission%20or%20collaboration">Submit work or collaborate</a></div><div><span>Finance Meta</span><a href="https://github.com/Finance-Meta-Research" target="_blank" rel="noreferrer">Research on GitHub</a><Link to="/login">Member sign in</Link><Link to="/evidence">About our research standards</Link></div><small>© {new Date().getFullYear()} Finance for All. Educational content, not personal financial advice.</small></footer>
    <nav className="ffa-dock" aria-label="Quick section navigation">{[{href:"#purpose",label:"Our story",icon:HeartHandshake},{href:"#programs",label:"Programs",icon:BookOpenText},{href:"#research",label:"Research",icon:FlaskConical},{href:"#community",label:"Community",icon:Globe2},{href:"#membership",label:"Membership",icon:Users}].map(({href,label,icon:Icon}) => <a href={href} key={href} aria-label={label}><Icon size={19} /><span>{label}</span></a>)}</nav>
  </div>;
}
